version: '3.8'

services:
  app:
    image: suryateja0900/devops_project:latest  # Use your Docker Hub image
    ports:
      - "5678:5678"
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: devops_db

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
