name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          kubectl config use-context minikube  # Change this if using a cloud cluster

      - name: Move to the `k8s/` Directory
        run: cd $GITHUB_WORKSPACE/k8s  # Ensure we are in the right folder

      - name: Deploy to Kubernetes
        run: |
          ls -l k8s  # List files in k8s to confirm they exist
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/postgres-service.yaml

      - name: Verify Deployment
        run: kubectl get pods -o wide

